name: deploy-on-gh-pages
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: node -v
      - run: npm -v
      - run: pwd
      - run: ls -la