name: deploy-on-gh-pages
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: git config --global user.email "laskov.lasko@gmail.com"
      - run: git config --global user.name "Lasko Laskov"
      - run: npm ci
      - run: npm run deploy